version: '3.9'
services:
  frontend:
    image: sarpio1237/shopping-ui
    container_name: frontend
    build: 
      context: ./front-end
    # links:
    #   - backend
    ports:
      [4200:4200]
    networks:
      - internalnet
    depends_on:
      - backend
  backend:
    image: sarpio1237/shopping-backend
    container_name: backend
    build: 
      context: ./backend
    ports:
      [8080:8080]
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
    