spring:
  datasource:
    url: jdbc:h2:mem:shopping
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
web:
  cors:
    allowed-origins: "*"
    allowed-method: GET, POST, DELETE, OPTIONS, HEAD
    allowed-header: "Requestor-Type"